name: stagehand_test
description: test-api-client.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  json_serializable: ^3.2.3

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
